# Changes here will be overwritten by Copier. NEVER EDIT MANUALLY.

_commit: 56e8180
_src_path: https://github.com/vivienm/copier-rust
author_name: Vivien Maisonneuve
copyright_holder: Vivien Maisonneuve
copyright_year: 2023
github_account: vivienm
github_pages: true
hosting_platform: github
license: MIT
package_name: uniq-ch
project_description: A Rust library for counting distinct elements in a stream, using
    ClickHouse uniq data structure.
project_name: uniq-ch
project_type: library
repo_name: rust-uniq-ch
rust_toolchain: stable
