# Changes here will be overwritten by Copier. NEVER EDIT MANUALLY.

_commit: 276a4c1
_src_path: gh:vivienm/copier-rust
author_fullname: Vivien Maisonneuve
copyright_holder: Vivien Maisonneuve
copyright_license: MIT
copyright_year: 2023
package_name: uniq-ch
pages_enabled: true
pages_provider: github.io
pages_url: https://vivienm.github.io/rust-uniq-ch
project_description: A Rust library for counting distinct elements in a stream, using
    ClickHouse uniq data structure.
project_name: uniq-ch
project_type: lib
repository_hosted: true
repository_name: rust-uniq-ch
repository_namespace: vivienm
repository_provider: github.com
repository_url: https://github.com/vivienm/rust-uniq-ch
rust_toolchain: nightly
