# Changes here will be overwritten by Copier. NEVER EDIT MANUALLY.

_commit: a557348
_src_path: gh:vivienm/copier-rust
author_fullname: Vivien Maisonneuve
copyright_date: '2022'
copyright_holder: Vivien Maisonneuve
copyright_license: MIT
package_name: uniq-ch
pages_enabled: true
project_description: A Rust library for counting distinct elements in a stream, using
    ClickHouse uniq data structure.
project_name: uniq-ch
project_type: lib
repository_name: rust-uniq-ch
repository_namespace: vivienm
repository_provider: github.com
