[package]
name = "uniq-ch"
version = "0.1.0"
edition = "2021"
description = "A Rust implementation of ClickHouse uniques hash sets."
repository = "https://github.com/vivienm/rust-uniq-ch/"
documentation = "https://vivienm.github.io/rust-uniq-ch/"
license = "MIT"

[dependencies]

[dev-dependencies]
anyhow = "1.0.62"
clap = { version = "3.2.17", features = ["derive"] }
plotters = { version = "0.3.3", default-features = false, features = ["area_series", "bitmap_backend", "bitmap_encoder"] }
